version: '3.8'

services:
  asic-web:
    image: longphamjustdoit/asicweb:latest
    container_name: asicweb
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_HOST=https://asicweb-portal.longpc.xyz
    restart: unless-stopped
    volumes:
      - ./next-cache:/app/.next/cache
    networks:
      - asicweb
networks:
  asicweb:
    external: true